<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings for the KIPMI Wallet authentication plugin.
 *
 * This file contains all English language strings used by the plugin,
 * including settings labels, descriptions, error messages, and user-facing text.
 * Translations to other languages should be contributed at lang.moodle.org.
 *
 * @package    auth_kipmi
 * @copyright  2025 Tinqin
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Plugin information
$string['pluginname'] = 'KIPMI Wallet Authentication';
$string['auth_kipmi_description'] = 'Authenticate users using KIPMI wallet and Verifiable Credentials (OIDC4VP).';

// Settings
$string['backend_url'] = 'Backend URL';
$string['backend_url_desc'] = 'URL of the authentication-be service (e.g., http://localhost:8081)';
$string['button_label'] = 'Login button label';
$string['button_label_desc'] = 'Text displayed on the KIPMI login button';
$string['map_field'] = 'User mapping field';
$string['map_field_desc'] = 'Which Moodle user field to map the verified personal_administrative_number to';
$string['autocreate'] = 'Auto-create users';
$string['autocreate_desc'] = 'Automatically create Moodle user accounts for verified wallet users if they don\'t exist';
$string['ssl_verify'] = 'Verify SSL certificates';
$string['ssl_verify_desc'] = 'Enable SSL certificate verification when calling authentication-be (disable only for local development)';
$string['default_firstname'] = 'Default first name';
$string['default_firstname_desc'] = 'Default first name to use when the wallet credential does not provide a given_name attribute';
$string['default_lastname'] = 'Default last name';
$string['default_lastname_desc'] = 'Default last name to use when the wallet credential does not provide a family_name attribute';

// Login page strings
$string['scan_with_wallet'] = 'Scan QR Code with KIPMI Wallet';
$string['scan_instructions'] = 'Open your KIPMI wallet app and scan this QR code to authenticate. The page will automatically continue once verification is complete.';
$string['qr_code_alt'] = 'KIPMI Authentication QR Code';

// Error messages
$string['auth_init_failed'] = 'Failed to initialize KIPMI authentication. Please check the backend URL configuration and try again.';
$string['invalid_state'] = 'Invalid authentication state. This may be a session timeout or security issue. Please try logging in again.';
$string['verification_failed'] = 'Wallet verification failed. Please try again.';
$string['no_user_identifier'] = 'No user identifier received from wallet. The wallet credential may be missing required attributes.';
$string['user_not_found'] = 'User not found in Moodle and auto-creation is disabled. Please contact your administrator.';
$string['user_creation_failed'] = 'Failed to create user account. Please contact your administrator.';

// Privacy API
$string['privacy:metadata'] = 'The KIPMI Wallet Authentication plugin does not store any personal data itself. It relies on verified credentials from the KIPMI wallet for authentication.';
$string['privacy:metadata:auth_kipmi_backend'] = 'The external authentication backend service that verifies KIPMI wallet credentials and manages authentication sessions.';
$string['privacy:metadata:auth_kipmi_backend:sessionid'] = 'A unique session identifier generated by Moodle to track the authentication request.';
$string['privacy:metadata:auth_kipmi_backend:personal_administrative_number'] = 'The user\'s personal administrative number extracted from their verified wallet credential, used to identify and match the user in Moodle.';
$string['privacy:metadata:auth_kipmi_backend:given_name'] = 'The user\'s first name extracted from their verified wallet credential.';
$string['privacy:metadata:auth_kipmi_backend:family_name'] = 'The user\'s last name extracted from their verified wallet credential.';
$string['privacy:metadata:auth_kipmi_backend:email'] = 'The user\'s email address extracted from their verified wallet credential.';
$string['privacy:metadata:auth_kipmi_session'] = 'Temporary session data stored during the KIPMI wallet authentication process. This data is automatically deleted after login completes or the session expires.';
$string['privacy:metadata:auth_kipmi_session:state'] = 'A CSRF protection token to prevent replay attacks during authentication.';
$string['privacy:metadata:auth_kipmi_session:sessionid'] = 'The unique session identifier for this authentication attempt.';
$string['privacy:metadata:auth_kipmi_session:wantsurl'] = 'The URL the user was trying to access before authentication, used for redirection after successful login.';
$string['privacy:metadata:auth_kipmi_session:starttime'] = 'The timestamp when the authentication session was initiated.';
